apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deploy
  namespace: default
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  replicas: 0
  selector:
    matchLabels:
      app: sample-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-deploy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sample-deploy
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        imagePullPolicy: IfNotPresent
        name: sample-deploy
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        karpenter.sh/nodepool: sample
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
      terminationGracePeriodSeconds: 0
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: sample-deploy
        matchLabelKeys:
        - pod-template-hash
        maxSkew: 1
        minDomains: 3
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
