apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelet-server-cert-untaint
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-server-cert-untaint-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kubelet-server-cert-untaint
subjects:
  - kind: ServiceAccount
    name: kubelet-server-cert-untaint
    namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kubelet-server-cert-untaint
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - patch
  - list
  - watch
