image:
  repository: "public.ecr.aws/g3x2k6s4/kscu"
  tag: "1.5@sha256:1afa578616b18ffb76b63506831baa859853978c5d1cf89fd9e6f91778469b4a"
  pullPolicy: IfNotPresent

taintKey: "example.com/kubelet-no-server-cert"
checkInterval: 5
logLevel: 4

resources:
  limits:
    cpu: 10m
    memory: 80Mi
  requests:
    cpu: 10m
    memory: 80Mi

nodeAffinity: {}

tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
